server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auca_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

urubutopay:
  base-url: https://staging.urubutopay.rw
  api-key: upg:test_sk_fc9b5563a9eb327e047d65353e9a293a:20e08c2ce27d1ccd3af9c900c71ba6a8
  merchant-code: TH43069310
  service-code: tuition-fees-7749
  callback-url: http://102.22.174.127:8080/api/payment/callback
  notification-url: http://102.22.174.127:8080/api/payment/notification
  auth-url: http://102.22.174.127:8080/auth/authenticate
  payer-verify-url: http://102.22.174.127:8080/payer/verify

jwt:
  secret: urubuto-webhook-secret-key-2024-auca-portal

webhook:
  username: urubuto_webhook
  password: webhook_password_2024